FastKartProject/Models/BasketViewModel.cs
namespace FastKartProject.Models;

public class BasketViewModel
{
    public int ProductId { get; set; }
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public double Price { get; set; }
    public int Count { get; set; }
}

FastKartProject/Models/ErrorViewModel.cs
namespace FastKartProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FastKartProject/Models/HeaderViewModel.cs
namespace FastKartProject.Models;

public class HeaderViewModel
{
    public List<BasketViewModel> BasketViewModels { get; set; } = new List<BasketViewModel>();
    public double TotalPrice { get; set; }
    public int Count { get; set; }
}

FastKartProject/Models/HomeViewModel.cs
using FastKartProject.DataAccessLayer.Entities;

namespace FastKartProject.Models;

public class HomeViewModel
{
    public List<Category> Categories{ get; set; } = new List<Category>();
    public List<Product> Products { get; set; } = new List<Product>();
}

FastKartProject/Models/WishlistViewModel.cs
namespace FastKartProject.Models;

public class WishlistViewModel
{
    public int ProductId { get; set; }
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public double Price { get; set; }
    public int Count { get; set; }
}

FastKartProject/Areas/AdminPanel/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace FastKartProject.Areas.AdminPanel.Controllers;

[Area("AdminPanel")]
public class AdminController : Controller
{

}

FastKartProject/Areas/AdminPanel/Controllers/CategoryController.cs
using FastKartProject.DataAccessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FastKartProject.Areas.AdminPanel.Controllers;

public class CategoryController : AdminController
{
    private readonly AppDbContext _dbContext;

    public CategoryController(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<IActionResult> Index()
    {
        var categoryList = await  _dbContext.Categories.ToListAsync();

        return View(categoryList);
    }

    public IActionResult Create()
    {
        return View();
    }

    public IActionResult Details(int? id)
    {
        return View();
    }
}

FastKartProject/Areas/AdminPanel/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace FastKartProject.Areas.AdminPanel.Controllers;

public class DashboardController : AdminController
{
    public IActionResult Index()
    {
        return View();
    }
}

FastKartProject/Controllers/HomeController.cs
using FastKartProject.DataAccessLayer;
using FastKartProject.DataAccessLayer.Entities;
using FastKartProject.Models;
using FastKartProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;

namespace FastKartProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _dbContext;
        private IBasketService _basketService;

        public HomeController(AppDbContext dbContext, IBasketService basketService)
        {
            _dbContext = dbContext;
            _basketService = basketService;
        }

        public IActionResult Index()
        {
            var categories = _dbContext.Categories.ToList();
            var product = _dbContext.Products.ToList();

            var model = new HomeViewModel()
            {
                Categories = categories,
                Products = product
            };
            return View(model);
        }

        public IActionResult GetBasket()
        {
            var newBasketViewModels = _basketService.GetBasket();

            return Json(newBasketViewModels);
        }

        public async Task<IActionResult> AddToBasket(int? id)
        {
           var result =  await _basketService.AddToBasket(id);

            if(result.Item1 == 0) return BadRequest(result.Item2);
            


            return RedirectToAction(nameof(Index));
        }

      


    }
}

FastKartProject/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace FastKartProject.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int? id)
        {
            ViewData["id"]=id;
            return View();
        }
    }
}

FastKartProject/Controllers/WishlistController.cs
using FastKartProject.DataAccessLayer;
using FastKartProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FastKartProject.Controllers
{
    public class WishlistController : Controller
    {
        private readonly AppDbContext _dbcontext;
        private IWishlistService _wishlisService;

        public WishlistController(AppDbContext dbcontext, IWishlistService wishlisService)
        {
            _dbcontext = dbcontext;
            _wishlisService = wishlisService;
        }

        public async Task<IActionResult> Index()
        {
            
            var newWishlistViewModels = await _wishlisService.GetWishlist();

            return View(newWishlistViewModels);
        }

        public async Task<IActionResult> AddToWishlist(int? id)
        {
            int result = await _wishlisService.AddToWishlist(id);

            if (result == 0)
                return BadRequest();

            return RedirectToAction(nameof(Index),"home");
        }
    }
}

FastKartProject/ViewComponents/FooterViewComponent.cs
using FastKartProject.DataAccessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;

namespace FastKartProject.ViewComponents;

public class FooterViewComponent : ViewComponent
{
    private readonly AppDbContext _dbContext;

    public FooterViewComponent(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    public async Task<ViewViewComponentResult> InvokeAsync()
    {
        var footer = await _dbContext.Footers.SingleOrDefaultAsync();

        return View(footer);
    }
}

FastKartProject/ViewComponents/HeaderViewComponent.cs
using FastKartProject.DataAccessLayer;
using FastKartProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace FastKartProject.ViewComponents;

public class HeaderViewComponent : ViewComponent
{
    private readonly AppDbContext _dbContext;

    public HeaderViewComponent(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    public async Task<ViewViewComponentResult> InvokeAsync()
    {
        var basketInString = Request.Cookies["basket"];

        if (string.IsNullOrEmpty(basketInString))
        {
            return View(new HeaderViewModel());
        }

        var basketViewModels = JsonConvert.DeserializeObject<List<BasketViewModel>>(basketInString);

        var newBasketViewModels = new List<BasketViewModel>();
        foreach (var product in basketViewModels)
        {
            var existProduct = _dbContext.Products.Find(product.ProductId);

            if (existProduct is null) continue;

            newBasketViewModels.Add(new BasketViewModel()
            {
                ProductId = existProduct.Id,
                ImageUrl = existProduct.ImageUrl,
                Price = existProduct.Price,
                Name = existProduct.Name,
                Count = product.Count
            });
        }

        double totalPrice = newBasketViewModels.Sum(x => x.Price * x.Count);
        int count = newBasketViewModels.Sum(x => x.Count);
        HeaderViewModel headerViewModel = new HeaderViewModel()
        {
            BasketViewModels = newBasketViewModels,
            TotalPrice = totalPrice,
            Count = count
        };

        return View(headerViewModel);

    }
}

FastKartProject/Areas/AdminPanel/Views/Category/Create.cshtml
<h1>Category Create</h1>

FastKartProject/Areas/AdminPanel/Views/Category/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

FastKartProject/Areas/AdminPanel/Views/Category/Index.cshtml
@model List<Category>
<div class="col-lg-12 grid-margin stretch-card" >
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic Table</h4>
            <p class="card-description">
                Add class <code>.table</code>
            </p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model)
                        {
                            <tr>
                                <td>@category.Name</td>
                                <td>@category.Description</td>
                                <td>
                                    <a class="btn btn-info btn-sm ">Details</a>
                                    <a class="btn btn-warning btn-sm ">Update</a>
                                    <a class="btn btn-danger btn-sm ">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

FastKartProject/Areas/AdminPanel/Views/Dashboard/Index.cshtml
<h1>Dashboard Index</h1>

FastKartProject/Views/Shared/Components/Footer/Default.cshtml
@model Footer  
<!-- Footer Section Start -->
<footer class="section-t-space footer-section-2 footer-color-3">
    <div class="container-fluid-lg">
        <div class="main-footer">
            <div class="row g-md-4 gy-sm-5">
                <div class="col-xxl-3 col-xl-4 col-sm-6">
                    <a href="index.html" class="foot-logo theme-logo">
                        <img src="../assets/images/logo/4.png" class="img-fluid blur-up lazyload" alt="">
                    </a>
                    <p class="information-text information-text-2">
                        it is a long established fact that a reader
                        will
                        be distracted by the readable content.
                    </p>
                    <ul class="social-icon">
                        <li class="light-bg">
                            <a href="@Model.FbLink" class="footer-link-color">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="light-bg">
                            <a href="https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&amp;flowEntry=ServiceLogin"
                               class="footer-link-color">
                                <i class="fab fa-google"></i>
                            </a>
                        </li>
                        <li class="light-bg">
                            <a href="https://twitter.com/i/flow/login" class="footer-link-color">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="light-bg">
                            <a href="@Model.InstLink" class="footer-link-color">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="light-bg">
                            <a href="https://in.pinterest.com/" class="footer-link-color">
                                <i class="fab fa-pinterest-p"></i>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="col-xxl-2 col-xl-4 col-sm-6">
                    <div class="footer-title">
                        <h4 class="text-white">About Fastkart</h4>
                    </div>
                    <ul class="footer-list footer-contact footer-list-light">
                        <li>
                            <a href="about-us.html" class="light-text">About Us</a>
                        </li>
                        <li>
                            <a href="contact-us.html" class="light-text">Contact Us</a>
                        </li>
                        <li>
                            <a href="term_condition.html" class="light-text">Terms & Coditions</a>
                        </li>
                        <li>
                            <a href="careers.html" class="light-text">Careers</a>
                        </li>
                        <li>
                            <a href="blog-list.html" class="light-text">Latest Blog</a>
                        </li>
                    </ul>
                </div>

                <div class="col-xxl-2 col-xl-4 col-sm-6">
                    <div class="footer-title">
                        <h4 class="text-white">Useful Link</h4>
                    </div>
                    <ul class="footer-list footer-list-light footer-contact">
                        <li>
                            <a href="order-success.html" class="light-text">Your Order</a>
                        </li>
                        <li>
                            <a href="user-dashboard.html" class="light-text">Your Account</a>
                        </li>
                        <li>
                            <a href="order-tracking.html" class="light-text">Track Orders</a>
                        </li>
                        <li>
                            <a href="wishlist.html" class="light-text">Your Wishlist</a>
                        </li>
                        <li>
                            <a href="faq.html" class="light-text">FAQs</a>
                        </li>
                    </ul>
                </div>

                <div class="col-xxl-2 col-xl-4 col-sm-6">
                    <div class="footer-title">
                        <h4 class="text-white">Categories</h4>
                    </div>
                    <ul class="footer-list footer-list-light footer-contact">
                        <li>
                            <a href="vegetables-demo.html" class="light-text">Fresh Vegetables</a>
                        </li>
                        <li>
                            <a href="spice-demo.html" class="light-text">Hot Spice</a>
                        </li>
                        <li>
                            <a href="bags-demo.html" class="light-text">Brand New Bags</a>
                        </li>
                        <li>
                            <a href="bakery-demo.html" class="light-text">New Bakery</a>
                        </li>
                        <li>
                            <a href="grocery-demo.html" class="light-text">New Grocery</a>
                        </li>
                    </ul>
                </div>

                <div class="col-xxl-3 col-xl-4 col-sm-6">
                    <div class="footer-title">
                        <h4 class="text-white">Store infomation</h4>
                    </div>
                    <ul class="footer-address footer-contact">
                        <li>
                            <a href="javascript:void(0)" class="light-text">
                                <div class="inform-box flex-start-box">
                                    <i data-feather="map-pin"></i>
                                    <p>Fastkart Demo Store, Demo store india 345 - 659</p>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="javascript:void(0)" class="light-text">
                                <div class="inform-box">
                                    <i data-feather="phone"></i>
                                    <p>Call us: 123-456-7890</p>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="javascript:void(0)" class="light-text">
                                <div class="inform-box">
                                    <i data-feather="mail"></i>
                                    <p>Email Us: Support@Fastkart.com</p>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="javascript:void(0)" class="light-text">
                                <div class="inform-box">
                                    <i data-feather="printer"></i>
                                    <p>Fax: 123456</p>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="sub-footer sub-footer-lite section-b-space section-t-space">
            <div class="left-footer">
                <p class="light-text">2022 Copyright By Themeforest Powered By Pixelstrap</p>
            </div>

            <ul class="payment-box">
                <li>
                    <img src="../assets/images/icon/paymant/visa.png" class="blur-up lazyload" alt="">
                </li>
                <li>
                    <img src="../assets/images/icon/paymant/discover.png" alt="" class="blur-up lazyload">
                </li>
                <li>
                    <img src="../assets/images/icon/paymant/american.png" alt="" class="blur-up lazyload">
                </li>
                <li>
                    <img src="../assets/images/icon/paymant/master-card.png" alt="" class="blur-up lazyload">
                </li>
                <li>
                    <img src="../assets/images/icon/paymant/giro-pay.png" alt="" class="blur-up lazyload">
                </li>
            </ul>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

FastKartProject/Views/Shared/_ProductsPartial.cshtml
@model List<Product>


<div class="row g-sm-4 g-3">
    <div class="col-xxl-12 ratio_110">
        <div class="slider-6 img-slider">
            @foreach (var product in Model)
            {
                <div>
                    <div class="product-box-5 wow fadeInUp">
                        <div class="product-image">
                            <a href="product-left-thumbnail.html">
                                <img src="~/assets/images/fashion/product/@product.ImageUrl"
                                     class="img-fluid blur-up lazyload bg-img" alt="">
                            </a>

                            <a asp-controller="Wishlist" asp-action="AddToWishlist" asp-route-id="@product.Id" class="wishlist-top" data-bs-toggle="tooltip"
                               data-bs-placement="top" title="Wishlist">
                                <i data-feather="bookmark"></i>
                            </a>

                            <ul class="product-option">
                                <li data-bs-toggle="tooltip" data-bs-placement="top" title="View">
                                    <a href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#view">
                                        <i data-feather="eye"></i>
                                    </a>
                                </li>

                                <li data-bs-toggle="tooltip" data-bs-placement="top" title="Compare">
                                    <a asp-controller="home" asp-action="addtobasket" asp-route-id="@product.Id">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart" b-luoaeh6s1k=""><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                                    </a>
                                </li>

                                <li data-bs-toggle="tooltip" data-bs-placement="top" title="Wishlist">
                                    <a asp-controller="Wishlist" asp-action="AddToWishlist" asp-route-id="@product.Id" class="notifi-wishlist">
                                        <i data-feather="heart"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="product-detail">
                            <a href="product-left-thumbnail.html">
                                <h5 class="name">@product.Name</h5>
                            </a>

                            <h5 class="sold text-content">
                                <span class="theme-color price">$@product.Price</span>
                                <del>28.56</del>
                            </h5>
                        </div>
                    </div>
                </div>

            }

        </div>
    </div>
</div>

FastKartProject/Views/Wishlist/Index.cshtml
@model List<WishlistViewModel>

<!-- Wishlist Section Start -->
<section class="wishlist-section section-b-space">
    <div class="container-fluid-lg">
        <div class="row g-sm-3 g-2 wishlist-item-js">
            @foreach (var product in Model)
            {
                <div class="col-xxl-2 col-lg-3 col-md-4 col-6 product-box-contain">
                    <div class="product-box-3 h-100">
                        <div class="product-header">
                            <div class="product-image">
                                <a href="product-left-thumbnail.html">
                                    <img src="~/assets/images/cake/product/@product.ImageUrl" class="img-fluid blur-up lazyload"
                                         alt="">
                                </a>

                                <div class="product-header-top">
                                    <button class="btn wishlist-button close_button remove-from-wl-js">
                                        <i data-feather="x"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="product-footer">
                            <div class="product-detail">
                                <span class="span-name">Vegetable</span>
                                <a href="product-left-thumbnail.html">
                                    <h5 class="name">@product.Name</h5>
                                </a>
                                <h6 class="unit mt-1">250 ml</h6>
                                <h5 class="price">
                                    <span class="theme-color">$@product.Price</span>
                                    <del>$15.15</del>
                                </h5>

                                <div class="add-to-cart-box bg-white mt-2">
                                    <button class="btn btn-add-cart addcart-button addproduct-wl-btn-js" asp-controller="wishlist" asp-action="addtowishlist" asp-route-id="@product.ProductId">
                                        Add
                                        <span class="add-icon bg-light-gray">
                                            <i class="fa-solid fa-plus"></i>
                                        </span>
                                    </button>
                                    <div class="cart_qty qty-box">
                                        <div class="input-group bg-white">
                                            <button type="button" class="qty-left-minus bg-gray" data-type="minus"
                                                    data-field="">
                                                <i class="fa fa-minus" aria-hidden="true"></i>
                                            </button>
                                            <input class="form-control input-number qty-input" type="text"
                                                   name="quantity" value="0">
                                            <button type="button" class="qty-right-plus bg-gray" data-type="plus"
                                                    data-field="">
                                                <i class="fa fa-plus" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            }
        </div>
    </div>
</section>
<!-- Wishlist Section End -->